name: Kubernetes App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t {your-image-name}:latest .
          docker tag {your-image-name}:latest {your-docker-registry}/{your-image-name}:latest

      - name: Push Docker Image to Amazon ECR
        run: |
          aws ecr get-login-password --region {your-region} | docker login --username AWS --password-stdin {your-account-id}.dkr.ecr.{your-region}.amazonaws.com
          docker push {your-docker-registry}/{your-image-name}:latest

      - name: Update Kubernetes Deployment
        run: kubectl apply -f deployments/app/
